# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fab332ed05a0e48bd86ed48972ef6073174ded32e0f5d905f213faca2b5d850c9cbdbde6668556c95f9bdf590b802562c58b1f7d77fa42db503247c194467b53

test:
  secret_key_base: a964a8aec3cd36e811001161817e66e0a57cd59c0a8706fd9b19f8841c185732efad744561a6f9716ad43f162c23a59c028a70fd947c3edfcff42c6a5418b822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
